### ISSUE TITLE
ParserError: (:) [], ParseException

### ISSUE THREAD

**Issue by Athok** [mjmeans/Appx-Backup#8]
In C:\Users\favre\OneDrive\Desktop\ps1\Appx-Backup.ps1:193 car:19
+               Sign&nbsp;up
+                   ~
E commerciale (&) non consentita. L'operatore & è riservato per utilizzi futuri. Utilizzare "&" per passare la e
commerciale come stringa.
In C:\Users\favre\OneDrive\Desktop\ps1\Appx-Backup.ps1:196 car:180
+ ... -details-target btn-link d-lg-none mt-1 color-fg-inherit">  <svg aria ...
+                                                                 ~
Operatore '<' riservato per utilizzi futuri.
In C:\Users\favre\OneDrive\Desktop\ps1\Appx-Backup.ps1:200 car:16
+ </button>      </div>
+                ~
Operatore '<' riservato per utilizzi futuri.
In C:\Users\favre\OneDrive\Desktop\ps1\Appx-Backup.ps1:205 car:148
+ ... -view-component="true" class="js-details-target btn-link">  <svg aria ...
+                                                                 ~
Operatore '<' riservato per utilizzi futuri.
In C:\Users\favre\OneDrive\Desktop\ps1\Appx-Backup.ps1:209 car:16
+ </button>      </div>
+                ~
Operatore '<' riservato per utilizzi futuri.
In C:\Users\favre\OneDrive\Desktop\ps1\Appx-Backup.ps1:224 car:7
+ </a>  </li>
+       ~
Operatore '<' riservato per utilizzi futuri.
In C:\Users\favre\OneDrive\Desktop\ps1\Appx-Backup.ps1:229 car:7
+ </a>  </li>
+       ~
Operatore '<' riservato per utilizzi futuri.
In C:\Users\favre\OneDrive\Desktop\ps1\Appx-Backup.ps1:234 car:7
+ </a>  </li>
+       ~
Operatore '<' riservato per utilizzi futuri.
In C:\Users\favre\OneDrive\Desktop\ps1\Appx-Backup.ps1:239 car:7
+ </a>  </li>
+       ~
Operatore '<' riservato per utilizzi futuri.
In C:\Users\favre\OneDrive\Desktop\ps1\Appx-Backup.ps1:244 car:7
+ </a>  </li>
+       ~
Operatore '<' riservato per utilizzi futuri.
Non sono stati segnalati tutti gli errori di analisi. Correggere gli errori segnalati e riprovare.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : AmpersandNotAllowed

**Comment by mjmeans** [comment]
You didn't download the file correctly. The '<' character doesn't exist in the Appx-Backup.ps1 file.

Learn how to use GitHub [here](https://docs.github.com/en/get-started) or google how to download a single file from GitHub.
